server:
  port: 8765

spring.application.name: spring-cloud-gateway
 
spring:
  cloud:
    gateway:
      routes:
       - id: users
         uri: http://localhost:8081/
         predicates:
          - Path= /users/*
       - id: jwt-session
         uri: http://localhost:8082/
         predicates:
           - Path= /token-session/* 

logging:
  level:
    org:
     springframework:
          cloud: 
           gateway: DEBUG
                   