server:
  port: 8765

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1600000000

spring:
  application:
   name: cloud-gateway-spring
  cloud:
    gateway:
     routes:
       - id: users
         uri: http://microservice-users.herokuapp.com
         predicates:
          - Path= /users/** , /users/userName/*
         filters:
          - name: Hystrix
            args:
             name: usersCircuitBreaker
             fallbackUri: forward:/users-fallback-uri
       - id: jwt-session
         uri:  http://ec2-13-232-254-45.ap-south-1.compute.amazonaws.com:8082/
         predicates:
           - Path= /token-session/*
         filters:
          - name: Hystrix
            args:
             name: jwtCircuitBreaker
             fallbackUri: forward:/jwt-session-fallback-uri
             
             
             
