server:
  port: 8765
  

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace

    
spring:
  application:
   name: cloud-gateway-spring
  cloud:
    gateway:
     routes:
       - id: users
         uri: http://microservice-users.herokuapp.com
         predicates:
          - Path= /users/*
       - id: jwt-session
         uri: http://jwt-session-microservice.herokuapp.com
         predicates:
           - Path= /token-session/*

        