server:
  port: 8765

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

spring:
  application:
    name: cloud-gateway-spring
  cloud:
    gateway:
      routes:
      - id: users
        uri: http://microservice-users.herokuapp.com
        predicates:
          - Path= /users/** , /users/userName/*
        filters:
          - name: Hystrix
            args:
             name: usersCircuitBreaker
             fallbackUri: forward:/users-fallback
        metadata:
          read-timeout: 20000
          connect-timeout: 4000
      - id: jwt-session
        uri: https://jwt-session-microservice.herokuapp.com/
        predicates:
           - Path= /token-session/*
        filters:
          - name: Hystrix
            args:
             name: jwtCircuitBreaker
             fallbackUri: forward:/jwt-session-fallback
        metadata:
          read-timeout: 20000
          connect-timeout: 4000
      - id: order-microservice
        uri: http://localhost:8083
        predicates:
           - Path= /orders/*
        filters:
           - name: Hystrix
             args:
              name: orderMicroserviceFallback
              fallbackUri: forward:/order-microservice-fallback
        metadata:
          read-timeout: 20000
          connect-timeout: 4000