server:
  port: 8765


spring:
  cloud:
    gateway:
      routes:
       - id: users
         uri: http://microservice-users.herokuapp.com:8081/
         predicates:
          - Path= /users/*
       - id: jwt-session
         uri: http://jwt-session-microservice.herokuapp.com:8082/
         predicates:
           - Path= /token-session/* 

logging:
  level:
    org:
     springframework:
          cloud: 
           gateway: DEBUG
                   